# Generated by Django 5.2 on 2025-06-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('organizer', 'Организатор мероприятий'), ('admin', 'Админ')], default='user', max_length=20),
        ),
    ]
